variables:
  ANDROID_COMPILE_SDK: '33'
  ANDROID_BUILD_TOOLS: '33.0.0'
  ANDROID_SDK_TOOLS: '9477386_latest'

stages:
  - build

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker image build --build-arg BASE_IMAGE=openjdk:${SDK_VERSION} --build-arg ANDROID_COMPILE_SDK=${ANDROID_COMPILE_SDK} --build-arg ANDROID_BUILD_TOOLS=${ANDROID_BUILD_TOOLS} --build-arg ANDROID_SDK_TOOLS=${ANDROID_SDK_TOOLS} -f ./Dockerfile -t $CI_REGISTRY_IMAGE:$SDK_VERSION .
    - docker image push $CI_REGISTRY_IMAGE:$SDK_VERSION
  parallel:
    matrix:
      - SDK_VERSION:
          - 11-jdk
          - 17-jdk-slim
  only:
    - main
